version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000 # localhost only by default
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
        - https-portal:https-portal
    depends_on:
      - mongo
      - elasticsearch
      - https-portal
    environment:
      - MONGO_URI=mongodb://mongo:27017/growi
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi
      - PASSWORD_SEED=keijo
      - FILE_UPLOAD=local     # activate this line if you use local storage of server rather than AWS

    command: "dockerize
              -wait tcp://mongo:27017
              -wait tcp://elasticsearch:9200
              -timeout 60s
              npm run server:prod"
    volumes:
      - growi_data:/data

  mongo:
    image: mongo:3.4
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db

  elasticsearch:
    image: elasticsearch:5.3-alpine
    #environment:
    #  - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # increase amount if you have enough memory
    command:
      - sh
      - -c
      - "./bin/elasticsearch-plugin list | grep -q analysis-kuromoji || ./bin/elasticsearch-plugin install analysis-kuromoji;
        ./bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu;
        /docker-entrypoint.sh elasticsearch"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_plugins:/usr/share/elasticsearch/plugins
      - ./esconfig:/usr/share/elasticsearch/config

  https-portal:
    image: steveltn/https-portal:1.5.0
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'wiki.soshikiz.com -> http://app:3000'
      STAGE: 'production'
      # FORCE_RENEW: 'true'

volumes:
  growi_data:
  mongo_configdb:
  mongo_db:
  es_data:
  es_plugins:
